/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.emirac.bonk;

public final class R {
    public static final class attr {
        /**  Name of the author of this component, e.g. Google. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int author=0x7f010001;
        /**  Reference to a the wallpaper's thumbnail bitmap. 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int thumbnail=0x7f010000;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int thumbnail=0x7f020001;
    }
    public static final class raw {
        public static final int bonksound=0x7f040000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int bonk_author=0x7f050004;
        public static final int bonk_desc=0x7f050003;
        public static final int bonk_name=0x7f050001;
        public static final int bonkquiet_name=0x7f050002;
    }
    public static final class xml {
        public static final int bonk=0x7f030000;
        public static final int bonkres2=0x7f030001;
    }
    public static final class styleable {
        /** Attributes that can be used with a bonk wallpaper.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #bonk wallpaper_author com.emirac.bonk:author}</code></td><td> Name of the author of this component, e.</td></tr>
           <tr><td><code>{@link #bonk wallpaper_thumbnail com.emirac.bonk:thumbnail}</code></td><td> Reference to a the wallpaper's thumbnail bitmap.</td></tr>
           </table>
           @see #bonk wallpaper_author
           @see #bonk wallpaper_thumbnail
         */
        public static final int[] bonk wallpaper = {
            0x7f010000, 0x7f010001
        };
        /**
          <p>
          @attr description
           Name of the author of this component, e.g. Google. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name android:author
        */
        public static final int bonk wallpaper_author = 1;
        /**
          <p>
          @attr description
           Reference to a the wallpaper's thumbnail bitmap. 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name android:thumbnail
        */
        public static final int bonk wallpaper_thumbnail = 0;
    };
}
